version: '2'

services:
  db:
    image: postgres:latest

    environment:
      POSTGRES_DB: "ClothesShop"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "userpass"

    networks:
      - online_store
    expose:
      - "5432"

  api:
    build: 
      context: .
      dockerfile: Dockerfile

    environment:
      - MAIL=sanyapridava@mail.ru
      - PASSWD=FWG43ewf3

    networks:
      - online_store
    expose:
      - "8000"

    depends_on:
      - db

  nginx:
    image: nginx:latest

    networks:
      - online_store
    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - api  

    restart: always

networks:
  online_store:
    driver: bridge
    


  

    
    

  
