version: '2'

services:

  api:
    build: 
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    depends_on:
      - db

  db:
    image: postgres:latest

    environment:
      POSTGRES_DB: "ClothesShop"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "userpass"

    ports:
      - "5432:5432"

    
    

  
