version: '2'

services:
  db:
    image: postgres:latest

    environment:
      POSTGRES_DB: "ClothesShop"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "userpass"

    ports:
      - "5432:5432"

  api:
    build: 
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - api  

    restart: always


  

    
    

  
